[extension]
id = "glass-dracula"
name = "Glass Dracula"
description = "Custom Dracula theme pack for Zed: Dark Vivid Black, Light Vivid White, Glass, Glass HSV, and Glass Vivid."
version = "0.2.0"
schema_version = 1
authors = ["BennyWu <3399930068@qq.com>"]
repository = "https://github.com/Aniu456/glass-dracula"

[themes]
